version: '3'

services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        env_file: .env
        ports:
            - "$NODE_PORT:$NODE_PORT"
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        command: /home/node/app/node_modules/.bin/nodemon server.js

volumes:
    node_modules: null
